import type { Vilt } from '../viltTypes'

export const faglar: Vilt[] = [
  {
    id: 'tjader',
    namn: 'Tjäder',
    latinNamn: 'Tetrao urogallus',
    kategoriId: 'skogsfaglar',
    emoji: '🦃',
    kortBeskrivning: 'Sveriges största hönsfågel och en symbolart för det nordiska skogslandskapet, starkt knuten till äldre barrskogar.',
    metaDescription: 'Lär dig allt om tjäder inför jägarexamen – utseende, beteende, jakttid, spår och förvaltning av Sveriges största skogsfågel.',
    fakta: {
      vikt: 'Tupp 3–5 kg, höna 1,5–2 kg',
      längd: '60–90 cm',
      livslängd: 'Upp till 12 år',
      jakttid: 'Varierar regionalt, vanligen september–november',
      status: 'Livskraftig men lokal minskning',
    },
    sektioner: [
      {
        rubrik: 'Introduktion',
        text: 'Tjäder Tetrao urogallus är Sveriges största hönsfågel och en symbolart för det nordiska skogslandskapet. Tjäder i Sverige förekommer främst i barrskogsområden där den är starkt knuten till äldre skogsmiljöer. Arten har stor betydelse för traditionell skogsfågeljakt och är ett uppskattat vilt bland jägare. Tjäder jakt ställer höga krav på kunskap om artens beteende och livsmiljö. För jägarexamenkandidater är förståelse för tjäder beteende och tjäder jakttid en viktig del av utbildningen. Arten är känslig för förändringar i skogsbruk och landskapsstruktur. En långsiktigt hållbar förvaltning är avgörande för att bevara livskraftiga bestånd.',
      },
      {
        rubrik: 'Utseende och kännetecken',
        text: 'Tjädern uppvisar tydlig könsskillnad i både storlek och utseende. Tuppen är betydligt större och kan väga upp mot fem kilo. Fjäderdräkten är mörk med grönskimrande bröst och röd hudfläck ovanför ögat. Stjärten är bred och rundad och hålls ofta uppfälld under spel. Hönan är mindre och har en mer diskret brun och svart spräcklig fjäderdräkt som ger god kamouflage. Näbben är kraftig och anpassad för att beta knoppar och barr. Vingarna är breda och ger ett karakteristiskt bullrande ljud vid uppflog.',
      },
      {
        rubrik: 'Utbredning och livsmiljö',
        text: 'Tjäder i Sverige förekommer från södra delarna av landet upp till fjällnära skogar i norr. Arten föredrar större sammanhängande barrskogar med inslag av tall. Äldre skog med varierad struktur ger både föda och skydd. Tjädern undviker i regel öppna jordbrukslandskap. Tillgång på lämpliga spelplatser är avgörande för reproduktion. Skogsbrukets utformning påverkar livsmiljön och därmed tätheten.',
      },
      {
        rubrik: 'Beteende och dygnsrytm',
        text: 'Tjäder beteende varierar över året. Under våren samlas tupparna på spelplatser där de utför ett karaktäristiskt spel för att locka hönor. Spelet sker tidigt på morgonen och är en central del av artens fortplantning. Under övriga delar av året lever tjädern mer diskret. Den är mest aktiv under morgon och kväll. Vid fara trycker hönan ofta hårt innan den flyger upp. Tuppen kan ibland sitta kvar i träd och förlita sig på kamouflage.',
      },
      {
        rubrik: 'Föda och näring',
        text: 'Tjädern är växtätare med diet som varierar efter årstid. Under vintern utgör tallbarr en viktig del av födan. Sommartid äter den örter, bär och insekter. Kycklingarna är beroende av insekter under sina första levnadsveckor. Födotillgången påverkar överlevnad och reproduktion. Näringsrika marker med blåbärsris är särskilt gynnsamma.',
      },
      {
        rubrik: 'Fortplantning',
        text: 'Parningen sker under våren i anslutning till spelet. Hönan lägger vanligtvis sex till åtta ägg i en enkel redegrop på marken. Ruvningen pågår i omkring fyra veckor. Kycklingarna är snabbt rörliga och följer modern direkt efter kläckning. Överlevnaden är beroende av väder och födotillgång. Predation från räv och mård påverkar kullarnas storlek.',
      },
      {
        rubrik: 'Spår och tecken',
        text: 'Spår av tjäder syns ofta som tre tydliga tår i snö eller mjuk mark. Spillningen är cylindrisk och kan innehålla barr under vintern. Fjädrar på marken kan indikera predation eller fällning. Spillning och betade tallar är vanliga vintertecken. Spelplatser kan identifieras genom fjädrar och trampad mark.',
      },
      {
        rubrik: 'Jakt i Sverige',
        text: 'Tjäder jakt bedrivs under fastställd tjäder jakttid som varierar regionalt. Jakten sker ofta som smygjakt eller med stående fågelhund. God artbestämning är viktig för att skilja mellan tupp och höna. Säker skottplacering kräver erfarenhet och lugn. Tjäder jakt är en traditionsrik jaktform som ställer krav på etik och kunskap.',
      },
      {
        rubrik: 'Förvaltning och bestånd',
        text: 'Beståndet av tjäder i Sverige varierar beroende på region och skogstillstånd. Förvaltningen bygger på reglerad jakt och hänsyn till reproduktionsutfall. Inventeringar genomförs lokalt för att följa utvecklingen. Skogsbrukets påverkan är en viktig faktor. En hållbar tjäder jakt förutsätter balans mellan avskjutning och återväxt. Tjädern är en indikatorart för äldre skog och ett värdefullt inslag i svensk jakttradition.',
      },
    ],
  },
  {
    id: 'orre',
    namn: 'Orre',
    latinNamn: 'Tetrao tetrix',
    kategoriId: 'skogsfaglar',
    emoji: '🐦',
    kortBeskrivning: 'En av Sveriges mest välkända skogshönsfåglar, starkt förknippad med öppna mossar och myrar där det karakteristiska vårspelet äger rum.',
    metaDescription: 'Lär dig allt om orre inför jägarexamen – utseende, beteende, jakttid, spår och förvaltning av orren i Sverige.',
    fakta: {
      vikt: 'Tupp 1–1,4 kg, höna 0,7–1 kg',
      längd: '40–55 cm',
      livslängd: 'Upp till 8 år',
      jakttid: 'Varierar regionalt, vanligen september–november',
      status: 'Livskraftig men lokalt minskande',
    },
    sektioner: [
      {
        rubrik: 'Introduktion',
        text: 'Orre Tetrao tetrix är en av Sveriges mest välkända skogshönsfåglar och en viktig art inom svensk småviltsjakt. Orre i Sverige förekommer i stora delar av landet där det finns lämpliga skogs och myrmarker. Arten är starkt förknippad med öppna mossar och myrar där det karakteristiska vårspelet äger rum. För jägare och jägarexamenkandidater är kunskap om orre beteende och livsmiljö central för både artkännedom och etisk jakt. Orre jakt är en traditionsrik jaktform som kräver god fältkunskap och respekt för artens reproduktion. Beståndet påverkas av habitatförändringar, predation och väderförhållanden under häckningstiden.',
      },
      {
        rubrik: 'Utseende och kännetecken',
        text: 'Orren uppvisar tydlig könsskillnad i både storlek och fjäderdräkt. Orrtuppen är större och har en svart fjäderdräkt med blåaktig glans. Ett tydligt kännetecken är den lyrformade stjärten och de vita vingbanden som syns väl i flykten. Över ögonen sitter röda hudflikar som framträder särskilt tydligt under spelet. Orr hönan är mindre och har en brun och svart spräcklig dräkt som ger god kamouflage. Näbben är kortare och anpassad för att beta knoppar och bär. Vingarna ger ett kraftigt buller vid uppflog.',
      },
      {
        rubrik: 'Utbredning och livsmiljö',
        text: 'Orre i Sverige förekommer från södra delarna upp till fjällnära områden i norr. Arten trivs i mosaiklandskap med ungskog, myrmarker och öppna hyggen. Särskilt viktiga är öppna spelplatser i anslutning till skyddande skog. Vintertid uppehåller sig orrar ofta i björk och tallskog där de finner föda. Livsmiljön påverkas starkt av skogsbrukets utformning. Variation i ålder och struktur i skogen gynnar arten.',
      },
      {
        rubrik: 'Beteende och dygnsrytm',
        text: 'Orre beteende varierar över året men är mest uppmärksammat under vårens spel. Tupparna samlas då på traditionella spelplatser där de spelar genom att bubbla och väsa samt visa upp stjärten. Spelet sker främst under tidig morgon. Under övriga delar av året lever orren mer diskret. Den är mest aktiv under morgon och kväll. Vintertid kan flockar av orrar ses beta i träd. Vid fara trycker fågeln hårt innan den flyger upp.',
      },
      {
        rubrik: 'Föda och näring',
        text: 'Orren är växtätare med diet som varierar efter årstid. Under vintern utgör björkknoppar och barr en viktig del av födan. Under sommarhalvåret äter den örter, frön och bär. Kycklingarna är beroende av insekter under sina första levnadsveckor. Födotillgången påverkar överlevnad och reproduktionsframgång. Områden med rik blåbärsvegetation är särskilt gynnsamma.',
      },
      {
        rubrik: 'Fortplantning',
        text: 'Parningen sker i anslutning till spelet under våren. Hönan lägger vanligtvis sex till åtta ägg i en enkel redegrop på marken. Ruvningen varar i cirka tre till fyra veckor. Kycklingarna är borymmare och lämnar boet kort efter kläckning. Modern ansvarar ensam för ungarna. Väder och predation påverkar kullarnas överlevnad i hög grad.',
      },
      {
        rubrik: 'Spår och tecken',
        text: 'Spår av orre syns som tre framåtriktade tår i snö eller mjuk mark. Spillningen är avlång och kan vintertid innehålla björkknoppar. Fjädrar på spelplatser är tydliga tecken under våren. Vintertid kan man se hål i snön där orrar grävt ner sig för skydd. Uppflog från mark ger ofta en tydlig ljudbild som avslöjar närvaro.',
      },
      {
        rubrik: 'Jakt i Sverige',
        text: 'Orre jakt bedrivs under fastställd orre jakttid som varierar mellan regioner. Jakten sker ofta med stående fågelhund eller som smygjakt. Artbestämning är viktig för att skilja mellan tupp och höna, särskilt under höstjakten. Säker skottplacering kräver lugn och erfarenhet. Etisk jakt innebär hänsyn till lokala bestånd och reproduktionsutfall. Orre jakt är en uppskattad del av svensk småviltsjakt och bygger på god fältkunskap.',
      },
      {
        rubrik: 'Förvaltning och bestånd',
        text: 'Beståndet av orre i Sverige varierar över tid och mellan regioner. Faktorer som skogsbruk, väder under kläckning och predation påverkar utvecklingen. Förvaltningen bygger på reglerad jakt och lokal anpassning. Inventering av spelplatser används som metod för att följa populationens status. En långsiktigt hållbar orre jakt förutsätter balans mellan avskjutning och reproduktion. Arten är en viktig indikator på fungerande skogs och myrmiljöer och har en självklar plats i svensk jakttradition.',
      },
    ],
  },
  {
    id: 'jarpe',
    namn: 'Järpe',
    latinNamn: 'Bonasa bonasia',
    kategoriId: 'skogsfaglar',
    emoji: '🐦',
    kortBeskrivning: 'Den minsta av Sveriges skogshönsfåglar, diskret och svårfångad, starkt knuten till äldre fuktiga barrblandskogar.',
    metaDescription: 'Lär dig allt om järpe inför jägarexamen – utseende, beteende, jakttid, spår och förvaltning av järpen i Sverige.',
    fakta: {
      vikt: '300–400 g',
      längd: '35–40 cm',
      livslängd: 'Upp till 7 år',
      jakttid: 'Begränsad, varierar regionalt',
      status: 'Livskraftig, lokalt känslig',
    },
    sektioner: [
      {
        rubrik: 'Introduktion',
        text: 'Järpe Bonasa bonasia är den minsta av Sveriges skogshönsfåglar och en diskret art som ofta undgår uppmärksamhet. Järpe i Sverige är knuten till fuktiga och variationsrika skogsmiljöer. Arten är mindre vanlig i intensivt brukade skogslandskap och gynnas av äldre blandskog. För jägare kräver järpe jakt god lokalkännedom och förståelse för artens försiktiga beteende. Kunskap om järpe beteende är viktig för både artbestämning och ansvarsfull jakt.',
      },
      {
        rubrik: 'Utseende och kännetecken',
        text: 'Järpen är betydligt mindre än orre och tjäder och väger omkring 300 till 400 gram. Fjäderdräkten är fint mönstrad i grått, brunt och svart vilket ger utmärkt kamouflage. Hanen har en tydlig svart haklapp med vit kant medan honan saknar den markerade kontrasten. Stjärten är relativt kort och rundad. I flykten är järpen snabb och låg, ofta med korta glidsträckor mellan träden.',
      },
      {
        rubrik: 'Utbredning och livsmiljö',
        text: 'Järpe i Sverige förekommer främst i skogslandskap från södra Sverige upp till mellersta Norrland. Arten föredrar tät granskog med inslag av lövträd och fuktiga partier. Närhet till bäckar och sumpskog är ofta gynnsamt. Den undviker öppna hyggen och stora kalytor. Livsmiljöns kvalitet är avgörande för lokala bestånd.',
      },
      {
        rubrik: 'Beteende och dygnsrytm',
        text: 'Järpe beteende präglas av stillsamhet och god förmåga att trycka hårt vid fara. Arten lever ofta parvis eller i små familjegrupper. Den är mest aktiv under morgon och kväll. Vid uppflog sker flykten snabbt och lågt genom skogen. Läten används för kontakt mellan individer, särskilt under våren.',
      },
      {
        rubrik: 'Föda och näring',
        text: 'Järpen är växtätare och lever av knoppar, blad, bär och frön. Under vintern utgör björkknoppar en viktig del av dieten. Kycklingarna är beroende av insekter under sina första levnadsveckor. Födotillgången påverkar överlevnaden. Variationsrik skog med rik undervegetation gynnar arten.',
      },
      {
        rubrik: 'Fortplantning',
        text: 'Parningen sker under våren. Honan lägger vanligtvis sju till tio ägg i en enkel redegrop på marken. Ruvningen varar i cirka tre veckor. Kycklingarna är borymmare och följer modern kort efter kläckning. Överlevnaden påverkas av väder och predation.',
      },
      {
        rubrik: 'Spår och tecken',
        text: 'Spår av järpe är små med tre tydliga tår i snö eller mjuk mark. Spillningen är liten och avlång. Fjädrar och spillning kan avslöja närvaro i täta skogspartier. Uppflog sker ofta plötsligt och kan vara den första indikationen på artens närvaro.',
      },
      {
        rubrik: 'Jakt i Sverige',
        text: 'Järpe jakt bedrivs under fastställd jakttid och är relativt begränsad jämfört med annan skogsfågeljakt. Jakten sker ofta med stående fågelhund. Artbestämning är viktig för att undvika förväxling med andra skogshöns. Försiktighet och återhållsamhet är viktiga inslag i jakten.',
      },
      {
        rubrik: 'Förvaltning och bestånd',
        text: 'Beståndet av järpe i Sverige varierar beroende på skogstillstånd och habitatkvalitet. Intensivt skogsbruk kan påverka arten negativt. Förvaltningen bygger på reglerad jakt och hänsyn till lokala bestånd. Bevarande av variationsrik skog är centralt för artens framtid.',
      },
    ],
  },
  {
    id: 'dalripa',
    namn: 'Dalripa',
    latinNamn: 'Lagopus lagopus',
    kategoriId: 'skogsfaglar',
    emoji: '🐦',
    kortBeskrivning: 'Karaktärsart för fjällnära skog och myrmarker i norra Sverige, känd för sitt säsongsbyten av fjäderdräkt från brunt till heltvitt.',
    metaDescription: 'Lär dig allt om dalripa inför jägarexamen – utseende, beteende, jakttid, spår och förvaltning av dalripan i Sverige.',
    fakta: {
      vikt: '400–650 g',
      längd: '37–42 cm',
      livslängd: 'Upp till 7 år',
      jakttid: 'Varierar regionalt, fjällområden',
      status: 'Livskraftig, beståndsvariationer förekommer',
    },
    sektioner: [
      {
        rubrik: 'Introduktion',
        text: 'Dalripa Lagopus lagopus är en karaktärsart för fjällnära skog och myrmarker. Dalripa i Sverige förekommer främst i norra delarna av landet. Arten är betydelsefull för fjälljakt och är uppskattad inom småviltsjakten. Kunskap om dalripa beteende är avgörande för framgångsrik och ansvarsfull jakt.',
      },
      {
        rubrik: 'Utseende och kännetecken',
        text: 'Dalripan byter fjäderdräkt efter årstid. Under vintern är den helt vit med svart stjärtband. Sommartid är fjäderdräkten brunmönstrad vilket ger god kamouflage. Hanen har under häckningstid röd hudfläck ovanför ögat. Kroppen är kompakt med fjäderbeklädda ben.',
      },
      {
        rubrik: 'Utbredning och livsmiljö',
        text: 'Dalripa i Sverige förekommer främst i fjällbjörkskog och på myrmarker i norr. Arten trivs i öppna och halvöppna miljöer med låg vegetation. Den rör sig mellan skog och öppnare marker beroende på årstid. Livsmiljön påverkas av klimat och snöförhållanden.',
      },
      {
        rubrik: 'Beteende och dygnsrytm',
        text: 'Dalripa beteende präglas av flockbildning under höst och vinter. Under våren blir den mer territoriell. Den är mest aktiv under morgon och kväll. Vid fara trycker den ofta hårt innan uppflog. Flykten är snabb och låg över marken.',
      },
      {
        rubrik: 'Föda och näring',
        text: 'Dalripan lever av knoppar, blad och bär. Vintertid är björkknoppar en viktig födokälla. Kycklingarna äter insekter under sina första veckor. Födotillgång och väder påverkar kullarnas överlevnad.',
      },
      {
        rubrik: 'Fortplantning',
        text: 'Häckningen sker under våren. Honan lägger vanligtvis sex till tio ägg i en redegrop på marken. Ruvningen varar omkring tre veckor. Kycklingarna är borymmare och följer modern direkt. Predation och väder påverkar reproduktionsframgången.',
      },
      {
        rubrik: 'Spår och tecken',
        text: 'Spår av dalripa syns tydligt i snö med fjäderbeklädda fötter som ger karaktäristiska avtryck. Spillningen är avlång och kan vintertid innehålla björkknoppar. Snögropar används som skydd vid hårt väder.',
      },
      {
        rubrik: 'Jakt i Sverige',
        text: 'Dalripa jakt bedrivs under fastställd jakttid i fjällområden. Jakten sker ofta med stående fågelhund. God kondition och terrängkännedom krävs. Artbestämning är viktig i områden där fjällripa förekommer.',
      },
      {
        rubrik: 'Förvaltning och bestånd',
        text: 'Beståndet av dalripa varierar kraftigt mellan år beroende på väder och smågnagartillgång. Förvaltningen bygger på årlig uppföljning och reglerad jakt. Hållbar avskjutning är avgörande för långsiktig stabilitet.',
      },
    ],
  },
  {
    id: 'fjallripa',
    namn: 'Fjällripa',
    latinNamn: 'Lagopus muta',
    kategoriId: 'skogsfaglar',
    emoji: '🐦',
    kortBeskrivning: 'Höggfjällsart som lever ovan trädgränsen i karg stenig terräng, anpassad till ett av Skandinaviens hårdaste klimat.',
    metaDescription: 'Lär dig allt om fjällripa inför jägarexamen – utseende, beteende, jakttid, spår och förvaltning av fjällripan i Sverige.',
    fakta: {
      vikt: '400–600 g',
      längd: '34–39 cm',
      livslängd: 'Upp till 8 år',
      jakttid: 'Reglerad, varierar regionalt',
      status: 'Livskraftig, klimatkänslig',
    },
    sektioner: [
      {
        rubrik: 'Introduktion',
        text: 'Fjällripa Lagopus muta är en högfjällsart som lever i mer karg terräng än dalripan. Fjällripa i Sverige förekommer främst ovan trädgränsen. Arten är anpassad till hårt klimat och öppna fjällhedar. För jägare är fjällripa jakt en krävande form av fjälljakt.',
      },
      {
        rubrik: 'Utseende och kännetecken',
        text: 'Fjällripan är något mindre och mer kompakt än dalripan. Vintertid är den helt vit med svart ögonstreck hos hanen. Sommartid är fjäderdräkten gråbrun och väl anpassad till stenig terräng. Benen är fjäderklädda vilket skyddar mot kyla.',
      },
      {
        rubrik: 'Utbredning och livsmiljö',
        text: 'Fjällripa i Sverige lever ovan trädgränsen i öppna och steniga fjällmiljöer. Den föredrar torrare och mer exponerade områden än dalripan. Livsmiljön är ofta karg med låg vegetation.',
      },
      {
        rubrik: 'Beteende och dygnsrytm',
        text: 'Fjällripa beteende präglas av god anpassning till fjällklimatet. Den är aktiv under morgon och kväll. Under vintern kan den gräva ner sig i snön för skydd. Flykten är snabb och låg över marken.',
      },
      {
        rubrik: 'Föda och näring',
        text: 'Födan består av knoppar, blad och fjällväxter. Vintertid äter den knoppar från dvärgbjörk och vide. Kycklingarna är beroende av insekter under sina första veckor.',
      },
      {
        rubrik: 'Fortplantning',
        text: 'Häckningen sker under försommaren. Honan lägger vanligtvis sex till åtta ägg i en markgrop. Ruvningen varar cirka tre veckor. Kycklingarna följer modern direkt efter kläckning.',
      },
      {
        rubrik: 'Spår och tecken',
        text: 'Spår i snö visar fjäderbeklädda fötter med tydliga tåavtryck. Spillningen är liten och mörk. Snögropar i exponerad terräng är vanliga vintertecken.',
      },
      {
        rubrik: 'Jakt i Sverige',
        text: 'Fjällripa jakt bedrivs under reglerad jakttid i fjällområden. Jakten kräver god fjällvana och säkerhetstänk. Artbestämning är viktig för att skilja från dalripa.',
      },
      {
        rubrik: 'Förvaltning och bestånd',
        text: 'Beståndet av fjällripa varierar mellan år beroende på klimat och predation. Förvaltningen bygger på inventering och anpassad jakt. Hållbar jakt är avgörande för att bevara stabila populationer i fjällmiljön.',
      },
    ],
  },
  {
    id: 'grasand',
    namn: 'Gräsand',
    latinNamn: 'Anas platyrhynchos',
    kategoriId: 'vattenFaglar',
    emoji: '🦆',
    kortBeskrivning: 'Sveriges vanligaste and och grundarten inom sjöfågeljakt, anpassningsbar och förekommande vid alla typer av vatten i hela landet.',
    metaDescription: 'Lär dig allt om gräsand inför jägarexamen – utseende, beteende, jakttid, spår och förvaltning av gräsanden i Sverige.',
    fakta: {
      vikt: 'Hane 1–1,5 kg, hona 0,9–1,2 kg',
      längd: '50–65 cm',
      livslängd: 'Upp till 20 år',
      jakttid: 'Varierar regionalt, höst/vinter',
      status: 'Livskraftig, stabil',
    },
    sektioner: [
      { rubrik: 'Introduktion', text: 'Gräsand Anas platyrhynchos är Sveriges vanligaste and och en grundart inom svensk sjöfågeljakt. Gräsand i Sverige förekommer i hela landet där det finns öppet vatten. Arten är anpassningsbar och lever i sjöar, dammar, kustvikar och stadsmiljöer. För jägare är gräsand jakt en viktig del av höstens fågeljakt. Kunskap om gräsand beteende och flyttningsmönster är central för en lyckad och etisk jakt.' },
      { rubrik: 'Utseende och kännetecken', text: 'Hanen har under häckningstid grönskimrande huvud, gul näbb och grå kropp. Honan är spräckligt brun och väl kamouflerad. Båda könen har en blå vingspegel med vit kant. Kroppen är relativt stor och kraftig jämfört med andra änder. I flykten är vingslagen snabba och jämna.' },
      { rubrik: 'Utbredning och livsmiljö', text: 'Gräsand i Sverige finns i såväl inland som kust. Arten häckar vid näringsrika sjöar, dammar och lugna vikar. Den är vanlig även i urbana miljöer. Tillgång på grunt vatten med vegetation är viktigt.' },
      { rubrik: 'Beteende och dygnsrytm', text: 'Gräsand beteende präglas av stor anpassningsförmåga. Den är mest aktiv under morgon och kväll. Arten betar i grunt vatten genom att tippa fram kroppen. Under flyttning samlas stora flockar.' },
      { rubrik: 'Föda och näring', text: 'Födan består av vattenväxter, frön och smådjur. Den äter även insekter och snäckor. Födotillgången påverkar häckningsframgången.' },
      { rubrik: 'Fortplantning', text: 'Häckning sker under våren. Honan lägger vanligen åtta till tolv ägg. Ruvningen varar omkring fyra veckor. Ungarna är snabbt simkunniga.' },
      { rubrik: 'Spår och tecken', text: 'Spår syns sällan tydligt men fjädrar och spillning finns vid strandkanter. Spillningen är lös och grönaktig. Ruggningsplatser kan avslöja närvaro.' },
      { rubrik: 'Jakt i Sverige', text: 'Gräsand jakt bedrivs under fastställd jakttid. Jakten sker ofta som kvällsjakt vid vatten. Artbestämning är viktig i blandade flockar.' },
      { rubrik: 'Förvaltning och bestånd', text: 'Beståndet av gräsand i Sverige är generellt stabilt. Utsättning förekommer lokalt. Förvaltningen bygger på reglerad jakt och våtmarksvård.' },
    ],
  },
  {
    id: 'kricka',
    namn: 'Kricka',
    latinNamn: 'Anas crecca',
    kategoriId: 'vattenFaglar',
    emoji: '🦆',
    kortBeskrivning: 'En liten snabb and som häckar vid myrar och småsjöar i norra Sverige, populär under höstflyttning bland sjöfågeljägare.',
    metaDescription: 'Lär dig allt om kricka inför jägarexamen – utseende, beteende, jakttid, spår och förvaltning av krickan i Sverige.',
    fakta: {
      vikt: '200–400 g',
      längd: '34–38 cm',
      livslängd: 'Upp till 20 år',
      jakttid: 'Höst/vinter, varierar regionalt',
      status: 'Livskraftig',
    },
    sektioner: [
      { rubrik: 'Introduktion', text: 'Kricka Anas crecca är en liten och snabb and som förekommer i stora delar av Sverige. Kricka i Sverige är vanlig under flyttning och i häckningstid i norra och mellersta delarna. Arten är uppskattad inom småskalig sjöfågeljakt.' },
      { rubrik: 'Utseende och kännetecken', text: 'Hanen har kastanjebrunt huvud med grön ögonfläck. Honan är diskret brun. Båda könen har grön vingspegel. Arten är betydligt mindre än gräsand.' },
      { rubrik: 'Utbredning och livsmiljö', text: 'Kricka i Sverige häckar vid små sjöar och myrar. Den föredrar vegetationsrika våtmarker. Under flyttning ses den även vid kust.' },
      { rubrik: 'Beteende och dygnsrytm', text: 'Kricka beteende präglas av vaksamhet och snabba uppflog. Den är mest aktiv i gryning och skymning. Flockar bildas ofta under hösten.' },
      { rubrik: 'Föda och näring', text: 'Födan består av frön, växtdelar och smådjur. Den betar i grunt vatten.' },
      { rubrik: 'Fortplantning', text: 'Honan lägger åtta till tio ägg. Ruvningen varar cirka tre veckor. Ungarna är snabbt självständiga.' },
      { rubrik: 'Spår och tecken', text: 'Små fjädrar och spillning vid strandkanten kan avslöja närvaro. Uppflog sker plötsligt och snabbt.' },
      { rubrik: 'Jakt i Sverige', text: 'Kricka jakt sker under andjakten på hösten. Artbestämning är viktig på grund av likhet med andra små änder.' },
      { rubrik: 'Förvaltning och bestånd', text: 'Beståndet varierar beroende på våtmarkernas kvalitet. Våtmarksvård är central för arten.' },
    ],
  },
  {
    id: 'vigg',
    namn: 'Vigg',
    latinNamn: 'Aythya fuligula',
    kategoriId: 'vattenFaglar',
    emoji: '🦆',
    kortBeskrivning: 'En dykand med karakteristisk nacktofs hos hanen, häckar vid inlandssjöar och ses i stora flockar vid kust under vinter.',
    metaDescription: 'Lär dig allt om vigg inför jägarexamen – utseende, beteende, jakttid, spår och förvaltning av viggen i Sverige.',
    fakta: {
      vikt: '550–900 g',
      längd: '40–47 cm',
      livslängd: 'Upp till 14 år',
      jakttid: 'Begränsad, höst',
      status: 'Livskraftig',
    },
    sektioner: [
      { rubrik: 'Introduktion', text: 'Vigg Aythya fuligula är en dykand som häckar i norra och mellersta Sverige. Vigg i Sverige är vanlig under flyttning och vinter i kustvatten. Arten jagas i begränsad omfattning.' },
      { rubrik: 'Utseende och kännetecken', text: 'Hanen är svart och vit med tydlig nacktofs. Honan är brun med ljusare kinder. Kroppen är kompakt.' },
      { rubrik: 'Utbredning och livsmiljö', text: 'Viggen häckar vid sjöar och tjärnar. Vintertid ses den i kustnära vatten.' },
      { rubrik: 'Beteende och dygnsrytm', text: 'Vigg beteende präglas av dykning efter föda. Den är aktiv under dagtid. Flockar bildas ofta under höst och vinter.' },
      { rubrik: 'Föda och näring', text: 'Den lever av musslor, snäckor och smådjur. Födan hämtas genom dykning.' },
      { rubrik: 'Fortplantning', text: 'Honan lägger åtta till elva ägg. Ruvning sker under cirka fyra veckor.' },
      { rubrik: 'Spår och tecken', text: 'Spår syns sällan men fjädrar kan hittas vid strand.' },
      { rubrik: 'Jakt i Sverige', text: 'Vigg jakt bedrivs under andjakten där arten förekommer. Noggrann artbestämning är viktig.' },
      { rubrik: 'Förvaltning och bestånd', text: 'Beståndet är stabilt men påverkas av vattenkvalitet. Förvaltningen bygger på reglerad jakt.' },
    ],
  },
  {
    id: 'knipa',
    namn: 'Knipa',
    latinNamn: 'Bucephala clangula',
    kategoriId: 'vattenFaglar',
    emoji: '🦆',
    kortBeskrivning: 'En dykand känd för sitt karaktäristiska visslande vingljud i flykten, häckar i hålträd vid skogssjöar i hela Sverige.',
    metaDescription: 'Lär dig allt om knipa inför jägarexamen – utseende, beteende, jakttid, spår och förvaltning av knipan i Sverige.',
    fakta: {
      vikt: '700–1 000 g',
      längd: '40–48 cm',
      livslängd: 'Upp till 14 år',
      jakttid: 'Höst/vinter',
      status: 'Livskraftig',
    },
    sektioner: [
      { rubrik: 'Introduktion', text: 'Knipa Bucephala clangula är en dykand som är känd för sitt visslande vingljud i flykten. Knipa i Sverige häckar i skogs och sjölandskap.' },
      { rubrik: 'Utseende och kännetecken', text: 'Hanen är svart och vit med rund vit kindfläck. Honan har brunt huvud och grå kropp.' },
      { rubrik: 'Utbredning och livsmiljö', text: 'Knipan häckar i hålträd vid sjöar. Den finns i hela landet där lämpliga miljöer finns.' },
      { rubrik: 'Beteende och dygnsrytm', text: 'Knipa beteende inkluderar dykning efter föda. Den är dagaktiv och vaksam.' },
      { rubrik: 'Föda och näring', text: 'Födan består av småfisk och vattenlevande djur.' },
      { rubrik: 'Fortplantning', text: 'Honan lägger ägg i trädhålor. Ungarna hoppar från bohålet kort efter kläckning.' },
      { rubrik: 'Spår och tecken', text: 'Fjädrar och spillning kan ses vid strand. Bohål nära vatten är typiska.' },
      { rubrik: 'Jakt i Sverige', text: 'Knipa jakt förekommer under andjakten. Artbestämning är viktig.' },
      { rubrik: 'Förvaltning och bestånd', text: 'Beståndet är stabilt. Holkuppsättning kan gynna arten.' },
    ],
  },
  {
    id: 'ejder',
    namn: 'Ejder',
    latinNamn: 'Somateria mollissima',
    kategoriId: 'vattenFaglar',
    emoji: '🦆',
    kortBeskrivning: 'En stor havsand starkt knuten till skärgård och kust, känd för sitt mjuka dun som använts i täcken i århundraden.',
    metaDescription: 'Lär dig allt om ejder inför jägarexamen – utseende, beteende, jakt, spår och förvaltning av ejdern i Sverige.',
    fakta: {
      vikt: '1,5–2,8 kg',
      längd: '50–70 cm',
      livslängd: 'Upp till 20 år',
      jakttid: 'Starkt begränsad, kontrollera aktuella regler',
      status: 'Minskande lokalt',
    },
    sektioner: [
      { rubrik: 'Introduktion', text: 'Ejder Somateria mollissima är en havslevande and som förekommer längs kusterna. Ejder i Sverige är starkt knuten till skärgårdsmiljöer.' },
      { rubrik: 'Utseende och kännetecken', text: 'Hanen är svart och vit med gröna nackpartier. Honan är brunmönstrad. Kroppen är kraftig.' },
      { rubrik: 'Utbredning och livsmiljö', text: 'Ejdern häckar i skärgårdar och kustnära områden. Den vistas större delen av året till havs.' },
      { rubrik: 'Beteende och dygnsrytm', text: 'Ejder beteende präglas av dykning efter musslor. Den är dagaktiv.' },
      { rubrik: 'Föda och näring', text: 'Blåmusslor utgör huvudföda. Arten kan dyka djupt.' },
      { rubrik: 'Fortplantning', text: 'Honan lägger fyra till sex ägg i bo på marken. Ruvning sker under cirka fyra veckor.' },
      { rubrik: 'Spår och tecken', text: 'Fjädrar och dun vid häckningsplatser är typiska tecken.' },
      { rubrik: 'Jakt i Sverige', text: 'Ejder jakt är idag starkt begränsad. Regler varierar och ska alltid kontrolleras.' },
      { rubrik: 'Förvaltning och bestånd', text: 'Beståndet har minskat i delar av Östersjön. Förvaltning fokuserar på övervakning och skydd.' },
    ],
  },
  {
    id: 'gragas',
    namn: 'Grågås',
    latinNamn: 'Anser anser',
    kategoriId: 'vattenFaglar',
    emoji: '🪿',
    kortBeskrivning: 'En stor gås som kraftigt ökat i antal, häckar vid sjöar och kust i hela Sverige och är ett viktigt jaktvilt under hösten.',
    metaDescription: 'Lär dig allt om grågås inför jägarexamen – utseende, beteende, jakttid, spår och förvaltning av grågåsen i Sverige.',
    fakta: {
      vikt: '2,5–4 kg',
      längd: '75–90 cm',
      livslängd: 'Upp till 20 år',
      jakttid: 'Höst, varierar regionalt',
      status: 'Livskraftig, ökande',
    },
    sektioner: [
      { rubrik: 'Introduktion', text: 'Grågås Anser anser är en stor gås som ökat kraftigt i antal. Grågås i Sverige häckar i många våtmarker och kustmiljöer. Arten har betydelse både för jakt och jordbruk.' },
      { rubrik: 'Utseende och kännetecken', text: 'Grågåsen är stor och gråbrun med orange näbb. Halsen är relativt lång och kraftig.' },
      { rubrik: 'Utbredning och livsmiljö', text: 'Arten förekommer i hela landet där det finns våtmarker. Den häckar vid sjöar och kust.' },
      { rubrik: 'Beteende och dygnsrytm', text: 'Grågås beteende inkluderar flockliv och tydliga varningsläten. Den betar ofta på åkrar.' },
      { rubrik: 'Föda och näring', text: 'Födan består av gräs och grödor.' },
      { rubrik: 'Fortplantning', text: 'Honan lägger fyra till sex ägg. Båda föräldrarna vaktar ungarna.' },
      { rubrik: 'Spår och tecken', text: 'Spillning och betade fält är tydliga tecken.' },
      { rubrik: 'Jakt i Sverige', text: 'Grågås jakt bedrivs under fastställd jakttid. Skyddsjakt förekommer vid skador.' },
      { rubrik: 'Förvaltning och bestånd', text: 'Beståndet är starkt växande. Förvaltningen syftar till balans mellan jakt och jordbruksintressen.' },
    ],
  },
  {
    id: 'kanadagas',
    namn: 'Kanadagås',
    latinNamn: 'Branta canadensis',
    kategoriId: 'vattenFaglar',
    emoji: '🪿',
    kortBeskrivning: 'En introducerad nordamerikansk gås som etablerat sig starkt i Sverige, igenkänns på svart hals och vit kindfläck.',
    metaDescription: 'Lär dig allt om kanadagås inför jägarexamen – utseende, beteende, jakttid, spår och förvaltning av kanadagåsen i Sverige.',
    fakta: {
      vikt: '3–6 kg',
      längd: '90–110 cm',
      livslängd: 'Upp till 20 år',
      jakttid: 'Höst, varierar regionalt',
      status: 'Livskraftig, ökande',
    },
    sektioner: [
      { rubrik: 'Introduktion', text: 'Kanadagås Branta canadensis är en introducerad art som etablerat sig i Sverige. Kanadagås i Sverige är vanlig vid sjöar och parker.' },
      { rubrik: 'Utseende och kännetecken', text: 'Arten är stor med svart hals och vit kindfläck. Kroppen är brungrå.' },
      { rubrik: 'Utbredning och livsmiljö', text: 'Den förekommer i hela landet nära vatten. Anpassningsförmågan är stor.' },
      { rubrik: 'Beteende och dygnsrytm', text: 'Kanadagås beteende präglas av flockliv. Den betar ofta på gräsytor.' },
      { rubrik: 'Föda och näring', text: 'Födan består främst av gräs och jordbruksgrödor.' },
      { rubrik: 'Fortplantning', text: 'Honan lägger fem till sju ägg. Föräldrarna försvarar ungarna aktivt.' },
      { rubrik: 'Spår och tecken', text: 'Spillning på gräsytor är vanligt. Flockar syns ofta öppet.' },
      { rubrik: 'Jakt i Sverige', text: 'Kanadagås jakt är vanlig och reglerad. Skyddsjakt används vid behov.' },
      { rubrik: 'Förvaltning och bestånd', text: 'Beståndet är livskraftigt. Förvaltningen syftar till att begränsa skador och hålla populationen på hållbar nivå.' },
    ],
  },
  {
    id: 'fasan',
    namn: 'Fasan',
    latinNamn: 'Phasianus colchicus',
    kategoriId: 'ovrigaFaglar',
    emoji: '🦃',
    kortBeskrivning: 'En introducerad art med stor betydelse för svensk småviltsjakt, häckar i öppna jordbrukslandskap med buskage och kantzoner.',
    metaDescription: 'Lär dig allt om fasan inför jägarexamen – utseende, beteende, jakttid, spår och förvaltning av fasanen i Sverige.',
    fakta: { vikt: 'Tupp 1–1,7 kg, höna 0,7–1 kg', längd: '53–89 cm', livslängd: 'Upp till 7 år', jakttid: 'Höst/vinter', status: 'Livskraftig, stöds av utsättning' },
    sektioner: [
      { rubrik: 'Introduktion', text: 'Fasan Phasianus colchicus är en introducerad art som haft stor betydelse för svensk småviltsjakt. Fasan i Sverige förekommer främst i jordbrukslandskap i södra och mellersta delarna. Arten är starkt knuten till öppna marker med inslag av skyddande vegetation. Fasan jakt är en traditionsrik jaktform som ofta bedrivs med stående fågelhund. God kunskap om artens livsmiljö är viktig för hållbar förvaltning.' },
      { rubrik: 'Utseende och kännetecken', text: 'Tuppen är färgstark med kopparröd kropp, mörkgrönt huvud och röd hud kring ögat. Den har lång spetsig stjärt. Hönan är mindre och brunspräcklig med kortare stjärt. Flykten är snabb och bullrande med korta glidsträckor.' },
      { rubrik: 'Utbredning och livsmiljö', text: 'Fasan i Sverige finns främst i slättbygder med åkrar, viltåkrar och buskage. Tät vegetation är viktig för skydd. Arten är beroende av milda vintrar i nordligare delar.' },
      { rubrik: 'Beteende och dygnsrytm', text: 'Fasan beteende präglas av marklevande livsstil. Den är mest aktiv morgon och kväll. Vid fara springer den först innan den flyger upp.' },
      { rubrik: 'Föda och näring', text: 'Födan består av frön, spannmål och insekter. Kycklingar är beroende av insekter under uppväxten.' },
      { rubrik: 'Fortplantning', text: 'Honan lägger åtta till tolv ägg i rede på marken. Ruvning sker i cirka tre veckor.' },
      { rubrik: 'Spår och tecken', text: 'Spår visar tre framåtriktade tår. Fjädrar och spillning finns i kantzoner.' },
      { rubrik: 'Jakt i Sverige', text: 'Fasan jakt bedrivs under fastställd jakttid. Utsättning förekommer i vissa områden.' },
      { rubrik: 'Förvaltning och bestånd', text: 'Beståndet varierar lokalt. Förvaltningen bygger på habitatvård och reglerad jakt.' },
    ],
  },
  {
    id: 'rapphons',
    namn: 'Rapphöns',
    latinNamn: 'Perdix perdix',
    kategoriId: 'ovrigaFaglar',
    emoji: '🐦',
    kortBeskrivning: 'En ursprunglig jordbruksfågel som minskat kraftigt i Sverige, nu förekommande i begränsade bestånd på öppna slätter.',
    metaDescription: 'Lär dig allt om rapphöns inför jägarexamen – utseende, beteende, jakttid, spår och förvaltning av rapphönset i Sverige.',
    fakta: { vikt: '300–450 g', längd: '28–32 cm', livslängd: 'Upp till 5 år', jakttid: 'Begränsad, lokalt reglerad', status: 'Minskande, sårbar' },
    sektioner: [
      { rubrik: 'Introduktion', text: 'Rapphöns Perdix perdix är en jordbruksfågel som minskat kraftigt i Sverige. Rapphöns i Sverige förekommer främst i öppna slättlandskap. Arten är känslig för förändringar i jordbruket.' },
      { rubrik: 'Utseende och kännetecken', text: 'Rapphönan är gråbrun med orange ansikte. Båda könen har rund kropp och kort stjärt.' },
      { rubrik: 'Utbredning och livsmiljö', text: 'Arten lever i öppna åkerlandskap med inslag av buskage. Skyddande kantzoner är viktiga.' },
      { rubrik: 'Beteende och dygnsrytm', text: 'Rapphöns lever i kullar och är markbundna. De trycker hårt vid fara.' },
      { rubrik: 'Föda och näring', text: 'Födan består av frön och insekter. Ungarna är beroende av insekter.' },
      { rubrik: 'Fortplantning', text: 'Honan lägger upp till femton ägg. Ruvningen varar cirka tre veckor.' },
      { rubrik: 'Spår och tecken', text: 'Spår syns som små tretåiga avtryck. Spillning finns i åkermark.' },
      { rubrik: 'Jakt i Sverige', text: 'Jakt är begränsad och lokalt reglerad. Försiktighet är viktig.' },
      { rubrik: 'Förvaltning och bestånd', text: 'Beståndet är svagt. Förvaltning fokuserar på habitatförbättring.' },
    ],
  },
  {
    id: 'ringduva',
    namn: 'Ringduva',
    latinNamn: 'Columba palumbus',
    kategoriId: 'ovrigaFaglar',
    emoji: '🕊️',
    kortBeskrivning: 'Sveriges största duva, allmän i skogs- och jordbrukslandskap, populär som jaktvilt under höst och tidig vår.',
    metaDescription: 'Lär dig allt om ringduva inför jägarexamen – utseende, beteende, jakttid, spår och förvaltning av ringduvan i Sverige.',
    fakta: { vikt: '450–600 g', längd: '38–43 cm', livslängd: 'Upp till 15 år', jakttid: 'Höst och vår', status: 'Livskraftig' },
    sektioner: [
      { rubrik: 'Introduktion', text: 'Ringduva Columba palumbus är Sveriges största duva. Ringduva i Sverige är allmän i skogs och jordbrukslandskap. Arten är viktig inom småviltsjakten.' },
      { rubrik: 'Utseende och kännetecken', text: 'Grå kropp med vit halsfläck och vita vingband. Kraftig och snabb flykt.' },
      { rubrik: 'Utbredning och livsmiljö', text: 'Förekommer i hela landet utom i fjäll. Häckar i skog och parker.' },
      { rubrik: 'Beteende och dygnsrytm', text: 'Ringduva beteende inkluderar flockliv under höst. Aktiv dagtid.' },
      { rubrik: 'Föda och näring', text: 'Äter frön, spannmål och knoppar.' },
      { rubrik: 'Fortplantning', text: 'Två ägg läggs per kull. Flera kullar per säsong möjliga.' },
      { rubrik: 'Spår och tecken', text: 'Spillning under träd och fjädrar är vanliga tecken.' },
      { rubrik: 'Jakt i Sverige', text: 'Ringduva jakt bedrivs under höst och vår enligt regler. Lockjakt är vanlig metod.' },
      { rubrik: 'Förvaltning och bestånd', text: 'Beståndet är livskraftigt. Anpassningsförmågan är stor.' },
    ],
  },
  {
    id: 'morkulla',
    namn: 'Morkulla',
    latinNamn: 'Scolopax rusticola',
    kategoriId: 'ovrigaFaglar',
    emoji: '🐦',
    kortBeskrivning: 'En nattaktiv vadare i fuktig skogsmark, känd för hannens karaktäristiska kvällssträck under våren.',
    metaDescription: 'Lär dig allt om morkulla inför jägarexamen – utseende, beteende, jakttid, spår och förvaltning av morkullan i Sverige.',
    fakta: { vikt: '250–420 g', längd: '33–38 cm', livslängd: 'Upp till 10 år', jakttid: 'Vår (sträck)', status: 'Livskraftig' },
    sektioner: [
      { rubrik: 'Introduktion', text: 'Morkulla Scolopax rusticola är en vadare knuten till skogsmark. Morkulla i Sverige är känd för sitt kvällssträck under våren.' },
      { rubrik: 'Utseende och kännetecken', text: 'Brunmönstrad med lång rak näbb. Breda rundade vingar.' },
      { rubrik: 'Utbredning och livsmiljö', text: 'Häckar i fuktig skog i hela landet.' },
      { rubrik: 'Beteende och dygnsrytm', text: 'Morkulla beteende märks under skymningssträcket. Marklevande och skygg.' },
      { rubrik: 'Föda och näring', text: 'Lever av mask och smådjur i marken.' },
      { rubrik: 'Fortplantning', text: 'Fyra ägg läggs i rede på marken.' },
      { rubrik: 'Spår och tecken', text: 'Borrhål i mjuk mark visar födosök.' },
      { rubrik: 'Jakt i Sverige', text: 'Morkulla jakt sker under vårsträcket. Regler är noga fastställda.' },
      { rubrik: 'Förvaltning och bestånd', text: 'Beståndet är generellt stabilt. Förvaltning följer internationella riktlinjer.' },
    ],
  },
  {
    id: 'enkelbeckasin',
    namn: 'Enkelbeckasin',
    latinNamn: 'Gallinago gallinago',
    kategoriId: 'ovrigaFaglar',
    emoji: '🐦',
    kortBeskrivning: 'En liten vadare i myrar och fuktiga ängar, känd för hannens brummande spelljud och sicksackflykt vid uppflog.',
    metaDescription: 'Lär dig allt om enkelbeckasin inför jägarexamen – utseende, beteende, jakttid, spår och förvaltning i Sverige.',
    fakta: { vikt: '80–140 g', längd: '25–27 cm', livslängd: 'Upp till 10 år', jakttid: 'Höst', status: 'Livskraftig' },
    sektioner: [
      { rubrik: 'Introduktion', text: 'Enkelbeckasin Gallinago gallinago är en mindre vadare i våtmarker. Enkelbeckasin i Sverige är vanlig under häckning och flyttning.' },
      { rubrik: 'Utseende och kännetecken', text: 'Brunstrimmig med mycket lång näbb. Snabb sicksackflykt.' },
      { rubrik: 'Utbredning och livsmiljö', text: 'Häckar i myrar och fuktiga ängar.' },
      { rubrik: 'Beteende och dygnsrytm', text: 'Aktiv i gryning och skymning. Hannen spelar med brummande ljud.' },
      { rubrik: 'Föda och näring', text: 'Äter mask och insekter.' },
      { rubrik: 'Fortplantning', text: 'Fyra ägg läggs i markrede.' },
      { rubrik: 'Spår och tecken', text: 'Borrhål i mark och snabb uppflog är typiska tecken.' },
      { rubrik: 'Jakt i Sverige', text: 'Jakt bedrivs under hösten. Artbestämning är viktig.' },
      { rubrik: 'Förvaltning och bestånd', text: 'Beståndet är stabilt men beroende av våtmarker.' },
    ],
  },
  {
    id: 'kraka',
    namn: 'Kråka',
    latinNamn: 'Corvus cornix',
    kategoriId: 'ovrigaFaglar',
    emoji: '🐦',
    kortBeskrivning: 'En intelligent och anpassningsbar kråkfågel, allmän i hela Sverige och ett viktigt förvaltningsvilt med lång jakttid.',
    metaDescription: 'Lär dig allt om kråka inför jägarexamen – utseende, beteende, jakttid, spår och förvaltning av kråkan i Sverige.',
    fakta: { vikt: '450–600 g', längd: '44–51 cm', livslängd: 'Upp till 20 år', jakttid: 'Lång jakttid, varierar regionalt', status: 'Livskraftig' },
    sektioner: [
      { rubrik: 'Introduktion', text: 'Kråka Corvus cornix är en allmän fågel i Sverige. Kråka i Sverige är anpassningsbar och förekommer i varierade miljöer.' },
      { rubrik: 'Utseende och kännetecken', text: 'Grå kropp med svart huvud och vingar. Kraftig näbb.' },
      { rubrik: 'Utbredning och livsmiljö', text: 'Finns i hela landet. Häckar i träd och stolpar.' },
      { rubrik: 'Beteende och dygnsrytm', text: 'Intelligent och opportunistisk. Aktiv dagtid.' },
      { rubrik: 'Föda och näring', text: 'Allätare med bred diet.' },
      { rubrik: 'Fortplantning', text: 'Fyra till fem ägg läggs i trädbo.' },
      { rubrik: 'Spår och tecken', text: 'Bo i trädtoppar och högljudda läten.' },
      { rubrik: 'Jakt i Sverige', text: 'Kråka jakt bedrivs under lång jakttid. Skyddsjakt är vanlig.' },
      { rubrik: 'Förvaltning och bestånd', text: 'Beståndet är starkt. Förvaltning sker genom fri jakt inom regler.' },
    ],
  },
  {
    id: 'skata',
    namn: 'Skata',
    latinNamn: 'Pica pica',
    kategoriId: 'ovrigaFaglar',
    emoji: '🐦',
    kortBeskrivning: 'En välkänd svart och vit kråkfågel med lång stjärt och metallglans, förekommer i hela Sverige i stad och på landsbygd.',
    metaDescription: 'Lär dig allt om skata inför jägarexamen – utseende, beteende, jakttid, spår och förvaltning av skatan i Sverige.',
    fakta: { vikt: '180–270 g', längd: '40–51 cm inkl. stjärt', livslängd: 'Upp till 15 år', jakttid: 'Reglerad jakttid', status: 'Livskraftig' },
    sektioner: [
      { rubrik: 'Introduktion', text: 'Skata Pica pica är en välkänd kråkfågel i Sverige. Skata i Sverige förekommer i både stad och landsbygd.' },
      { rubrik: 'Utseende och kännetecken', text: 'Svart och vit med lång stjärt och metallglans.' },
      { rubrik: 'Utbredning och livsmiljö', text: 'Finns i hela landet utom fjällområden.' },
      { rubrik: 'Beteende och dygnsrytm', text: 'Intelligent och social. Aktiv dagtid.' },
      { rubrik: 'Föda och näring', text: 'Allätare med varierad diet.' },
      { rubrik: 'Fortplantning', text: 'Bygger stort risbo i träd. Fem till åtta ägg.' },
      { rubrik: 'Spår och tecken', text: 'Stora bon i trädtoppar är tydliga tecken.' },
      { rubrik: 'Jakt i Sverige', text: 'Skata jakt sker under reglerad jakttid.' },
      { rubrik: 'Förvaltning och bestånd', text: 'Beståndet är livskraftigt. Förvaltning sker genom jakt och lokal anpassning.' },
    ],
  },
]
