import type { Vilt } from '../viltTypes'

export const hardjur: Vilt[] = [
  {
    id: 'skogshare',
    namn: 'Skogshare',
    latinNamn: 'Lepus timidus',
    kategoriId: 'hardjur',
    emoji: '🐇',
    kortBeskrivning: 'Den ursprungliga svenska haren, väl anpassad till snörika vintrar med vit vinterpäls, klassisk art i traditionell harjakt med drivande hund.',
    metaDescription: 'Lär dig allt om skogshare inför jägarexamen – utseende, beteende, jakttid, spår och förvaltning av skogsharen i Sverige.',
    fakta: {
      vikt: '2,5–4 kg',
      längd: '46–65 cm',
      livslängd: 'Upp till 12 år',
      jakttid: 'Höst/vinter, varierar regionalt',
      status: 'Livskraftig',
    },
    sektioner: [
      { rubrik: 'Introduktion', text: 'Skogshare Lepus timidus är den ursprungliga haren i stora delar av Sverige och en klassisk art inom svensk småviltsjakt. Skogshare i Sverige förekommer från södra delarna upp till fjällkedjan. Arten är väl anpassad till kallt klimat och snörika vintrar. För jägare är kunskap om skogshare beteende avgörande vid jakt med drivande hund. Skogsharen har stor betydelse i traditionell harjakt och är ett uppskattat vilt.' },
      { rubrik: 'Utseende och kännetecken', text: 'Skogsharen är medelstor med relativt korta öron jämfört med fältharen. Pälsen är brungrå under sommarhalvåret och blir vit under vintern i större delen av landet. Svansens ovansida är vit vilket skiljer den från fältharen. Bakbenen är kraftiga och anpassade för snö. Kroppsformen är kompakt och anpassad till skogsmiljö.' },
      { rubrik: 'Utbredning och livsmiljö', text: 'Skogshare i Sverige finns i skogslandskap, myrmarker och fjällnära områden. Den trivs i varierad terräng med god tillgång på skydd. Tät ungskog och buskage är viktiga daglegor. Arten undviker öppna slättlandskap där fältharen dominerar.' },
      { rubrik: 'Beteende och dygnsrytm', text: 'Skogshare beteende präglas av nattaktivitet. Den ligger ofta tryckt i lega under dagen. Vid fara flyr den i snabba bukter för att förvilla rovdjur och hund. Hemområdena är relativt små.' },
      { rubrik: 'Föda och näring', text: 'Födan består av örter, gräs och ris under sommaren. Vintertid äter den kvistar och bark från buskar och träd. Födotillgången påverkar kondition och reproduktion.' },
      { rubrik: 'Fortplantning', text: 'Parningen inleds under våren. Honan kan få flera kullar per år. En kull består ofta av två till fyra ungar. Ungarna föds pälsade och med öppna ögon.' },
      { rubrik: 'Spår och tecken', text: 'Spår i snö visar kraftiga bakfötter framför de mindre framfötterna. Spillningen är rund och ljusbrun. Betade kvistar kan avslöja närvaro.' },
      { rubrik: 'Jakt i Sverige', text: 'Skogshare jakt bedrivs under fastställd jakttid, ofta med drivande hund. Jakten kräver god terrängkännedom och säker skottplacering. Artbestämning är viktig i områden där fälthare förekommer.' },
      { rubrik: 'Förvaltning och bestånd', text: 'Beståndet av skogshare i Sverige varierar regionalt. Klimat, predation och habitatförändringar påverkar utvecklingen. Förvaltningen bygger på reglerad jakt och lokal anpassning.' },
    ],
  },
  {
    id: 'falthare',
    namn: 'Fälthare',
    latinNamn: 'Lepus europaeus',
    kategoriId: 'hardjur',
    emoji: '🐇',
    kortBeskrivning: 'Större än skogsharen med brun päls året runt och svart svansovansida, knuten till öppna jordbrukslandskap i södra Sverige.',
    metaDescription: 'Lär dig allt om fälthare inför jägarexamen – utseende, beteende, jakttid, spår och förvaltning av fältharen i Sverige.',
    fakta: {
      vikt: '3–5 kg',
      längd: '52–68 cm',
      livslängd: 'Upp till 12 år',
      jakttid: 'Höst/vinter',
      status: 'Livskraftig',
    },
    sektioner: [
      { rubrik: 'Introduktion', text: 'Fälthare Lepus europaeus är större än skogsharen och förekommer främst i södra Sverige. Fälthare i Sverige är knuten till öppna jordbrukslandskap. Arten är en uppskattad del av harjakten i slättbygder.' },
      { rubrik: 'Utseende och kännetecken', text: 'Fältharen är större och har längre öron än skogsharen. Pälsen är brun året runt och blir inte helt vit vintertid. Svansens ovansida är svart vilket är ett tydligt kännetecken. Kroppen är långsträckt och kraftfull.' },
      { rubrik: 'Utbredning och livsmiljö', text: 'Fälthare i Sverige finns främst i södra och mellersta jordbruksområden. Den föredrar öppna fält med inslag av åkerholmar och diken. Tät vegetation ger skydd under dagtid.' },
      { rubrik: 'Beteende och dygnsrytm', text: 'Fälthare beteende liknar skogsharens men arten rör sig ofta över större ytor. Den är mest aktiv nattetid. Vid flykt springer den snabbt i vida cirklar.' },
      { rubrik: 'Föda och näring', text: 'Födan består av gräs, grödor och örter. Vintertid äts även bark och kvistar. Tillgång på jordbruksgrödor kan gynna beståndet.' },
      { rubrik: 'Fortplantning', text: 'Fältharen har hög reproduktion med flera kullar per år. Kullarna kan bestå av upp till fyra ungar. Ungarna är tidigt självständiga.' },
      { rubrik: 'Spår och tecken', text: 'Spår liknar skogsharens men är större. Spillning återfinns ofta på åkermark.' },
      { rubrik: 'Jakt i Sverige', text: 'Fälthare jakt bedrivs med drivande hund under fastställd jakttid. God säkerhet är viktig i öppet landskap.' },
      { rubrik: 'Förvaltning och bestånd', text: 'Beståndet varierar beroende på jordbruksmetoder och predation. Förvaltningen bygger på reglerad jakt och habitatvård.' },
    ],
  },
  {
    id: 'vildkanin',
    namn: 'Vildkanin',
    latinNamn: 'Oryctolagus cuniculus',
    kategoriId: 'hardjur',
    emoji: '🐇',
    kortBeskrivning: 'En introducerad art som lever i kolonier i sandiga marker och kustnära områden, kan orsaka lokala skador och jagas ofta som skyddsjakt.',
    metaDescription: 'Lär dig allt om vildkanin inför jägarexamen – utseende, beteende, jakttid, spår och förvaltning av vildkaninen i Sverige.',
    fakta: {
      vikt: '1,5–2,5 kg',
      längd: '34–50 cm',
      livslängd: 'Upp till 9 år',
      jakttid: 'Skyddsjakt, reglerad',
      status: 'Etablerad, lokal förekomst',
    },
    sektioner: [
      { rubrik: 'Introduktion', text: 'Vildkanin Oryctolagus cuniculus är en introducerad art i Sverige. Vildkanin i Sverige förekommer främst i södra delarna och i urbana miljöer. Arten kan lokalt orsaka skador på grödor och mark.' },
      { rubrik: 'Utseende och kännetecken', text: 'Vildkaninen är mindre än harar och har kortare öron. Pälsen är gråbrun. Svansen är kort med vit undersida. Kroppen är kompakt och låg.' },
      { rubrik: 'Utbredning och livsmiljö', text: 'Vildkanin i Sverige finns i sandiga marker, kustnära områden och parker. Den gräver omfattande gångsystem under marken. Tillgång till grävbar jord är avgörande.' },
      { rubrik: 'Beteende och dygnsrytm', text: 'Vildkanin beteende präglas av koloniliv. Den är mest aktiv under skymning och natt. Varningsstamp med bakbenen används vid fara.' },
      { rubrik: 'Föda och näring', text: 'Födan består av gräs, örter och grödor. Den kan orsaka betesskador på unga plantor.' },
      { rubrik: 'Fortplantning', text: 'Arten har mycket hög reproduktionsförmåga. Flera kullar per år är vanliga. Kullarna består ofta av fyra till åtta ungar.' },
      { rubrik: 'Spår och tecken', text: 'Små runda spillningskulor är typiska. Hålor och jordhögar visar närvaro.' },
      { rubrik: 'Jakt i Sverige', text: 'Vildkanin jakt bedrivs ofta som skyddsjakt. Fällor och jakt med hund förekommer.' },
      { rubrik: 'Förvaltning och bestånd', text: 'Beståndet kan variera kraftigt lokalt. Förvaltningen syftar ofta till att begränsa skador. Arten är etablerad i flera regioner och kräver aktiv hantering.' },
    ],
  },
]
